title: Mi Blog Personal
description: ""
author:
  name: "Marcos Scurtu"
  email: "marcoscurtu@gmail.com"
  url: "https://shurkon.github.io/Mi_Blog/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Marcos Scurtu"
year : "2025"
